//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMP_Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locatie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locatie()
        {
            this.EventLocaties = new HashSet<EventLocatie>();
            this.LocatieContacts = new HashSet<LocatieContact>();
        }
    
        public int id { get; set; }
        public string naam { get; set; }
        public string adres { get; set; }
        public string gemeente { get; set; }
        public string provincie { get; set; }
        public string gebouwType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventLocatie> EventLocaties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocatieContact> LocatieContacts { get; set; }
    }
}
